#!/usr/bin/env node
/*
 * Static site build for xorio.rs. No dependencies beyond Node ≥ 20.
 *
 *   node build.js          build the whole site into dist/
 *
 * Vercel runs this on every deploy and serves dist/ (see vercel.json), so
 * nothing in dist/ is committed: edit src/, never the generated output.
 * Local preview with live reload: `npm run dev`.
 *
 * Inputs:  src/*  project/data/stats.json  project/assets/img/dims.json
 *          project/assets/**  project/docs/**   (static files, copied as-is)
 * Outputs: dist/index.html  dist/p/<id>.html  dist/f/<key>.html
 *          dist/{about,experiments,contribute,privacy,404}.html
 *          dist/sitemap.xml  dist/robots.txt
 *          dist/project/assets/{site.css,app.js,theme.js}  (from src/)
 *
 * Every page is complete HTML (crawlers and link previews need no JS);
 * app.js only adds the terminal, filtering and the theme switch.
 */
'use strict';
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const ROOT = __dirname;
const OUT = path.join(ROOT, 'dist');
const D = require('./src/data');
const R = require('./src/render');

const read = f => fs.readFileSync(path.join(ROOT, f), 'utf8');
const readJson = f => JSON.parse(read(f));
const stats = fs.existsSync(path.join(ROOT, 'project/data/stats.json')) ? readJson('project/data/stats.json') : {};
const dims = fs.existsSync(path.join(ROOT, 'project/assets/img/dims.json')) ? readJson('project/assets/img/dims.json') : {};

// Generated assets are copied first so their hashes are known to asset().
const generated = {};

const outputs = {};   // path -> content (strings)
function emit(file, content) { outputs[file] = content; }

const hashCache = {};
function asset(p) {
  p = p.replace(/^\//, '');
  if (!(p in hashCache)) {
    const content = generated[p] !== undefined ? Buffer.from(generated[p]) : (fs.existsSync(path.join(ROOT, p)) ? fs.readFileSync(path.join(ROOT, p)) : null);
    if (content === null) throw new Error(`asset not found: ${p}`);
    hashCache[p] = crypto.createHash('sha1').update(content).digest('hex').slice(0, 8);
  }
  return `/${p}?v=${hashCache[p]}`;
}
// CSS-referenced files (fonts, the repo-card starfield) get the same ?v=
// hash as everything else, so the font preloads match the @font-face URLs
// and the immutable cache rule can never pin a stale file.
const banner = src => `/* Generated by build.js from ${src} — edit that file, not this one. */\n`;
generated['project/assets/site.css'] = banner('src/styles.css') + read('src/styles.css').replace(/url\((fonts|img)\/([^)]+)\)/g, (_, dir, f) => `url(${asset(`project/assets/${dir}/${f}`)})`);
generated['project/assets/app.js'] = banner('src/app.js') + read('src/app.js');
generated['project/assets/theme.js'] = banner('src/theme.js') + read('src/theme.js');
const ctx = { asset, dims, stats };

const shell = read('src/shell.html');
const sitemap = [];   // [url, priority] for every page given a priority
function page({ file, page: pageId, title, description, canonical, ogImage, jsonld, body, nav, headExtra, priority }) {
  if (priority) sitemap.push([canonical, priority]);
  // Function replacers throughout: a `$&`, `$'` or `$$` in content must
  // never be read as a replacement pattern.
  const lit = v => () => v;
  let html = shell
    .replace(/\{\{a:([^}]+)\}\}/g, (_, p) => asset(p))
    .replace(/\{\{site:(\w+)\}\}/g, (_, k) => { if (!D.SITE[k]) throw new Error(`shell.html: unknown {{site:${k}}}`); return R.esc(D.SITE[k]); })
    .replace(/\{\{title\}\}/g, lit(R.esc(title)))
    .replace(/\{\{description\}\}/g, lit(R.esc(description)))
    .replace(/\{\{canonical\}\}/g, lit(R.esc(canonical)))
    .replace(/\{\{og_image\}\}/g, lit(R.esc(ogImage)))
    .replace(/\{\{jsonld\}\}/g, lit(JSON.stringify(jsonld).replace(/</g, '\\u003c')))
    .replace(/\{\{head_extra\}\}/g, lit(headExtra || ''))
    .replace(/\{\{page\}\}/g, lit(pageId))
    .replace(/\{\{body\}\}/g, lit(body));
  if (nav) html = html.replace(`data-nav="${nav}"`, `data-nav="${nav}" aria-current="page"`);
  html = html.replace(/^<!DOCTYPE html>\n/i, m => m + '<!-- Generated by build.js from src/ — edit src/, not this file. -->\n');
  emit(file, html);
}

const SITE = D.SITE.url;
const ORG = {
  '@type': 'Organization', name: 'xorio', url: SITE + '/', logo: SITE + asset('project/assets/favicon-512.png'), email: D.SITE.email,
  founder: { '@type': 'Person', name: 'Radu Marias', url: D.SITE.founderGithub },
  sameAs: [D.SITE.github, D.SITE.founderGithub, D.SITE.discord, D.SITE.linkedin]
};
const OG_DEFAULT = SITE + asset('project/assets/og.jpg');

// ── Pages ──────────────────────────────────────────────
page({
  file: 'index.html', page: 'home', nav: 'home', priority: '1.0',
  title: D.SITE.title, description: D.SITE.description, canonical: SITE + '/', ogImage: OG_DEFAULT,
  jsonld: { '@context': 'https://schema.org', '@graph': [ORG, { '@type': 'WebSite', name: 'xorio', url: SITE + '/' }] },
  body: R.home(ctx)
});

// One prerendered page per filter (/f/<key>): linkable, crawlable, and
// the gallery arrives already filtered even without JavaScript.
for (const f of D.FILTERS.filter(x => x.key !== 'all')) {
  page({
    file: `f/${f.key}.html`, page: 'home', nav: f.key === 'oss' ? 'oss' : f.key === 'app' ? 'home' : null,
    title: R.filterTitle(f), priority: '0.6', description: `${f.label} projects from the xorio open-source collective.`,
    canonical: `${SITE}/f/${f.key}`, ogImage: OG_DEFAULT,
    jsonld: { '@context': 'https://schema.org', '@type': 'CollectionPage', name: `${f.label} — xorio`, url: `${SITE}/f/${f.key}`, isPartOf: { '@type': 'WebSite', name: 'xorio', url: SITE + '/' } },
    body: R.home(ctx, f.key)
  });
}
for (const p of D.PROJECTS) {
  const url = `${SITE}/p/${p.id}`;
  const og = p.shot ? SITE + asset(`project/assets/img/${p.shot}-og.jpg`) : OG_DEFAULT;
  const ld = p.kind === 'app'
    ? { '@context': 'https://schema.org', '@type': 'WebApplication', name: p.name, description: p.blurb, url: p.live || url, applicationCategory: 'WebApplication', operatingSystem: 'Any', author: ORG, ...(p.repo ? { codeRepository: p.repo } : {}) }
    : { '@context': 'https://schema.org', '@type': 'SoftwareSourceCode', name: p.name, description: p.blurb, url, codeRepository: p.repo, programmingLanguage: (p.tech || [])[0], author: ORG };
  page({
    file: `p/${p.id}.html`, page: 'detail', nav: null, priority: '0.7',
    title: `${p.name} — xorio`, description: p.blurb, canonical: url, ogImage: og, jsonld: ld,
    body: R.detail(p, ctx)
  });
}

page({ file: 'experiments.html', page: 'experiments', nav: 'experiments', priority: '0.8',
  title: 'Experiments & open ideas — xorio', description: `xorio's backlog of ${R.approx(D.EXPERIMENTS.length)} open experiments — agent tooling, security, filesystems and more. Many have no contributors yet; you could be the first.`,
  canonical: SITE + '/experiments', ogImage: OG_DEFAULT, jsonld: { '@context': 'https://schema.org', '@type': 'CollectionPage', name: 'Experiments & open ideas', url: SITE + '/experiments', isPartOf: { '@type': 'WebSite', url: SITE + '/' } },
  body: R.experiments(ctx) });

page({ file: 'about.html', page: 'about', nav: 'about', priority: '0.8',
  title: 'About — xorio', description: 'xorio is a Rust & STEM open-source collective founded by Radu Marias: high-performance systems, robust web services and secure applications, built in the open.',
  canonical: SITE + '/about', ogImage: OG_DEFAULT, jsonld: { '@context': 'https://schema.org', '@type': 'AboutPage', name: 'About xorio', url: SITE + '/about', mainEntity: ORG },
  body: R.about(ctx) });

page({ file: 'contribute.html', page: 'contribute', nav: 'contribute', priority: '0.8',
  title: 'Contribute — xorio', description: 'How to build with the xorio collective: pick a project, claim an issue, ship in the open. Discord, GitHub, email and good first issues.',
  canonical: SITE + '/contribute', ogImage: OG_DEFAULT, jsonld: { '@context': 'https://schema.org', '@type': 'WebPage', name: 'Contribute', url: SITE + '/contribute', isPartOf: { '@type': 'WebSite', url: SITE + '/' } },
  body: R.contribute(ctx) });

page({ file: 'privacy.html', page: 'privacy', nav: null, priority: '0.2',
  title: 'Privacy Policy — xorio', description: "Privacy policy for xorio's websites and mobile applications, including our Android apps published on Google Play.",
  canonical: SITE + '/privacy', ogImage: OG_DEFAULT, jsonld: { '@context': 'https://schema.org', '@type': 'WebPage', name: 'Privacy Policy', url: SITE + '/privacy' },
  body: read('src/privacy.html') });

page({ file: '404.html', page: 'notfound', nav: null,
  title: 'Not found — xorio', description: 'This page does not exist.', canonical: SITE + '/404', ogImage: OG_DEFAULT,
  jsonld: { '@context': 'https://schema.org', '@type': 'WebPage', name: 'Not found' },
  headExtra: '<meta name="robots" content="noindex">',
  body: R.notFound() });

// ── sitemap / robots ───────────────────────────────────
emit('sitemap.xml', `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n` +
  sitemap.map(([u, pr]) => `  <url><loc>${u}</loc><priority>${pr}</priority></url>`).join('\n') + '\n</urlset>\n');
emit('robots.txt', `User-agent: *\nAllow: /\nDisallow: /404\n\nSitemap: ${SITE}/sitemap.xml\n`);

Object.assign(outputs, generated);

// Static files under project/assets and project/docs are copied verbatim.
// dims.json is a build input only; the three generated assets come from src/.
const copies = {};   // dist-relative path -> absolute source path
(function walk(rel) {
  for (const e of fs.readdirSync(path.join(ROOT, rel), { withFileTypes: true })) {
    const r = rel + '/' + e.name;
    if (e.isDirectory()) walk(r);
    else if (!(r in outputs) && r !== 'project/assets/img/dims.json' && e.name !== '.DS_Store') copies[r] = path.join(ROOT, r);
  }
})('project/assets');
if (fs.existsSync(path.join(ROOT, 'project/docs'))) (function walk(rel) {
  for (const e of fs.readdirSync(path.join(ROOT, rel), { withFileTypes: true })) {
    const r = rel + '/' + e.name;
    if (e.isDirectory()) walk(r); else if (e.name !== '.DS_Store') copies[r] = path.join(ROOT, r);
  }
})('project/docs');

// ── Write dist/ ────────────────────────────────────────
// Files are only rewritten when their content changed, and anything left
// over from a previous build is removed, so dist/ never goes empty while
// `npm run dev` is serving it.
let changed = 0;
function put(rel, buf) {
  const abs = path.join(OUT, rel);
  if (fs.existsSync(abs) && fs.readFileSync(abs).equals(buf)) return;
  fs.mkdirSync(path.dirname(abs), { recursive: true });
  fs.writeFileSync(abs, buf);
  changed++;
}
for (const [rel, content] of Object.entries(outputs)) put(rel, Buffer.from(content));
for (const [rel, src] of Object.entries(copies)) put(rel, fs.readFileSync(src));

const keep = new Set([...Object.keys(outputs), ...Object.keys(copies)]);
(function sweep(rel) {
  const abs = path.join(OUT, rel);
  if (!fs.existsSync(abs)) return;
  for (const e of fs.readdirSync(abs, { withFileTypes: true })) {
    const r = rel ? rel + '/' + e.name : e.name;
    if (e.isDirectory()) { sweep(r); if (!fs.readdirSync(path.join(OUT, r)).length) fs.rmdirSync(path.join(OUT, r)); }
    else if (!keep.has(r)) { fs.unlinkSync(path.join(OUT, r)); changed++; }
  }
})('');

console.log(`Built dist/: ${keep.size} files (${changed} changed) — ${D.PROJECTS.length} project pages, ${D.EXPERIMENTS.length} experiments.`);
